MODULE := engines/hanekawa

MODULE_OBJS :=  \
	maya/agenda.o \
	maya/analysis.o \
	maya/argacces.o \
	maya/bload.o \
	maya/bmathfun.o \
	maya/bsave.o \
	maya/classcom.o \
	maya/classexm.o \
	maya/classfun.o \
	maya/classinf.o \
	maya/classini.o \
	maya/classpsr.o \
	maya/clsltpsr.o \
	maya/commline.o \
	maya/conscomp.o \
	maya/constrct.o \
	maya/constrnt.o \
	maya/crstrtgy.o \
	maya/cstrcbin.o \
	maya/cstrccom.o \
	maya/cstrcpsr.o \
	maya/cstrnbin.o \
	maya/cstrnchk.o \
	maya/cstrncmp.o \
	maya/cstrnops.o \
	maya/cstrnpsr.o \
	maya/cstrnutl.o \
	maya/default.o \
	maya/defins.o \
	maya/developr.o \
	maya/dffctbin.o \
	maya/dffctbsc.o \
	maya/dffctcmp.o \
	maya/dffctdef.o \
	maya/dffctpsr.o \
	maya/dffnxbin.o \
	maya/dffnxcmp.o \
	maya/dffnxexe.o \
	maya/dffnxfun.o \
	maya/dffnxpsr.o \
	maya/dfinsbin.o \
	maya/dfinscmp.o \
	maya/drive.o \
	maya/emathfun.o \
	maya/engine.o \
	maya/envrnmnt.o \
	maya/evaluatn.o \
	maya/expressn.o \
	maya/exprnbin.o \
	maya/exprnops.o \
	maya/exprnpsr.o \
	maya/extnfunc.o \
	maya/factbin.o \
	maya/factbld.o \
	maya/factcmp.o \
	maya/factcom.o \
	maya/factfun.o \
	maya/factgen.o \
	maya/facthsh.o \
	maya/factlhs.o \
	maya/factmch.o \
	maya/factmngr.o \
	maya/factprt.o \
	maya/factqpsr.o \
	maya/factqury.o \
	maya/factrete.o \
	maya/factrhs.o \
	maya/filecom.o \
	maya/filertr.o \
	maya/functional.o \
	maya/generate.o \
	maya/genrcbin.o \
	maya/genrccmp.o \
	maya/genrccom.o \
	maya/genrcexe.o \
	maya/genrcfun.o \
	maya/genrcpsr.o \
	maya/globlbin.o \
	maya/globlbsc.o \
	maya/globlcmp.o \
	maya/globlcom.o \
	maya/globldef.o \
	maya/globlpsr.o \
	maya/immthpsr.o \
	maya/incrrset.o \
	maya/inherpsr.o \
	maya/inscom.o \
	maya/insfile.o \
	maya/insfun.o \
	maya/insmngr.o \
	maya/insmoddp.o \
	maya/insmult.o \
	maya/inspsr.o \
	maya/insquery.o \
	maya/insqypsr.o \
	maya/iofun.o \
	maya/lgcldpnd.o \
	maya/maya.o \
	maya/memalloc.o \
	maya/miscfun.o \
	maya/modulbin.o \
	maya/modulbsc.o \
	maya/modulcmp.o \
	maya/moduldef.o \
	maya/modulpsr.o \
	maya/modulutl.o \
	maya/msgcom.o \
	maya/msgfun.o \
	maya/msgpass.o \
	maya/msgpsr.o \
	maya/multifld.o \
	maya/multifun.o \
	maya/objbin.o \
	maya/objcmp.o \
	maya/objrtbin.o \
	maya/objrtbld.o \
	maya/objrtcmp.o \
	maya/objrtfnx.o \
	maya/objrtgen.o \
	maya/objrtmch.o \
	maya/parsefun.o \
	maya/pattern.o \
	maya/pprint.o \
	maya/prccode.o \
	maya/prcdrfun.o \
	maya/prcdrpsr.o \
	maya/prdctfun.o \
	maya/prntutil.o \
	maya/proflfun.o \
	maya/reorder.o \
	maya/reteutil.o \
	maya/retract.o \
	maya/router.o \
	maya/rulebin.o \
	maya/rulebld.o \
	maya/rulebsc.o \
	maya/rulecmp.o \
	maya/rulecom.o \
	maya/rulecstr.o \
	maya/ruledef.o \
	maya/ruledlt.o \
	maya/rulelhs.o \
	maya/rulepsr.o \
	maya/scanner.o \
	maya/sortfun.o \
	maya/strngfun.o \
	maya/strngrtr.o \
	maya/symblbin.o \
	maya/symblcmp.o \
	maya/symbol.o \
	maya/sysdep.o \
	maya/textpro.o \
	maya/tmpltbin.o \
	maya/tmpltbsc.o \
	maya/tmpltcmp.o \
	maya/tmpltdef.o \
	maya/tmpltfun.o \
	maya/tmpltlhs.o \
	maya/tmpltpsr.o \
	maya/tmpltrhs.o \
	maya/tmpltutl.o \
	maya/userdata.o \
	maya/userfunctions.o \
	maya/utility.o \
	maya/watch.o \
	hanekawa.o 


# this module can be build as a plugin
ifeq ($(ENABLE_HANEKAWA), DYNAMIC_PLUGIN)
PLUGIN := 1
endif 

# Include common rules
include $(srcdir)/rules.mk
